name: Continout Integration

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  CI_BUILD_NUMBER_BASE: ${{ github.run_number }}
  CI_TARGET_BRANCH: ${{ github.head_ref || github.ref_name }}
  TRIGGER: ${{ github.event_name }}

jobs:
  build:

    # We need to run on Windows as we're supporting .NET Framework
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v5
    #   with:
    #     dotnet-version: 10.0.x
    # - name: Compute and set build number
    #   shell: bash
    #   run: |
    #       echo "CI_BUILD_NUMBER=$(($CI_BUILD_NUMBER_BASE+1000))" >> $GITHUB_ENV
    - name: TEST PR RUN CHECK
      shell: bash
      run: |
          echo "$TRIGGER"
    # - name: Build & Push
    #   env:
    #     DOTNET_CLI_TELEMTRY_OPTOUT: true
    #     DUMMY: ${{ secrets.DUMMY }}
    #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   shell: pwsh
    #   run: |
    #     ./Build.ps1